#!/bin/bash

ORIGINAL=`git branch | grep \* | cut -d ' ' -f2`
MERGE_BRANCH=$1
git checkout $MERGE_BRANCH
git pull
echo "Generating patch"
git format-patch $MERGE_BRANCH --no-color --stdout > temp.patch
echo "Checking if merge is possible"
if [ -s temp.patch ] 
then
        git apply temp.patch --check
else
        echo "Completely mergeable"
fi

git checkout $ORIGINAL
rm temp.patch
